(function(){
  function protectObject(a,b,c){function d(){/*for(;;){}*/}function e(a,b,c){a[b]=c}function f(a,b){"use strict";let c=0,d=a.length,e=!1;for(;c<d&&!e;)e=!!b(a[c],c),c++}function g(a){"use strict";if(a==e)return!0;let c=!1;return f(b,function(b){if(b==a)return c=!0,!0}),c}function h(a){"use strict";if("constructor"!=a&&"hasOwnProperty"!=a&&"isPrototypeOf"!=a&&"propertyIsEnumerable"!=a&&"toLocaleString"!=a&&"toString"!=a&&"valueOf"!=a){let b=!1;try{b=delete Object.prototype[a]}catch(a){}return b}return!1}if(!a)return{error:new Error(`[antiHook.js] [protectObject] No object passed. Can not protect undefined object.`),code:"dummy"};if(!b)return{error:new Error(`[antiHook.js] [protectObject] No accessorFunction passed, object will be unaccessable. Can not protect object.`),code:"dummy"};let i={},j={};for(const d in a)if(h(d))j[d]=a[d],a[d]=null;else return{error:new Error(`[antiHook.js] [protectObject] Object proto could not be safely cleared. Either your object has an invalid name or security has been broken.`),code:"runtime"};for(const f in a){let b=delete a[f];if(!1==b)return{error:new Error(`[antiHook.js] [protectObject] Object has non configurable property (property: ${f}). Can not protect object.`),code:"runtime"};i[f]=a[f];let h={get:!1,set:!1,thisFunc:arguments.callee},k=function(){if(!h.get)return void(h.get=k.caller==h.thisFunc);let a=k.caller,b=!1,c="unknown";return"function"==typeof a&&function(){'use strict';"r"==a.name&&`function r(e){let t=this;const n=JSON.parse(e);for(let e=0,i=n.length;e<i;++e)t=t[n[e]];return t}`==a.toString()&&(b=!0,c="Chrome")}(),null===a&&(b=!0),b?(d(),{}):a?g(a)?i[f]:void 0:void 0},l=function(a){if(!h.set)return void(h.set=l.caller==h.thisFunc);let b=l.caller;b&&g(b)&&(i[f]=a)};if(function(){'use strict';Object.defineProperty(a,f,{configurable:!!c,get:k,set:l})}(),!c){let b=delete a[f];if(b)return{error:new Error(`[antiHook.js] [protectObject] Property did not pass security checks. Configurable should be false but is true. Most likely tampering.`),code:"security"}}if(a[f]=a[f],!h.get||!h.set)return{error:new Error(`[antiHook.js] [protectObject] Property did not pass security checks. Getter and Setter not properly initialize. Most likely tampering.`),code:"security"};e(a,f,j[f])}return!0}

  let safe = true;

  // Exposing object globably pretending like you already got it from hacking the game.
  window.player = {name: "timmy", health: 100};
  window.getPlayer = function(){return (safe)? {name: player.name, health: player.health} : "Tampered"};
  window.setPlayer = function(_set){if (safe){player.name = (_set.name)? _set.name : player.name; player.health = (_set.health)? _set.health: player.health;}}
  let protReturn = protectObject(player, [getPlayer, setPlayer]);
  safe = (protReturn === true);
  console.log(`Protected Object Safe: ${safe}. Protection return:`, protReturn);
})();
